version: '3.1'
services:
  database:
    container_name: api-container
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: default-database
    ports:
      - "5432:5432"
